### ISSUE TITLE
Can't find RegionRenderer

### ISSUE THREAD

**Issue by Xalaber** [TOGoS/TMCMR#24] opened 2015-02-23 00:57 UTC
Error: Could not find or load main class togos.minecraft.maprend.RegionRenderer

Anyways I compiled this and ran it according to the instructions on http://www.nuke24.net/projects/TMCMR/
and every time I get that error.

I even went as far as looking in the actual .jar file and saw that it WAS in there. Now this is either an issue or I'm doing something wrong.
I did the following:
1. I'm on Linux Mint 17.1 Cinnamon
2. Downloaded the zip file of the master branch
3. Extracted the folder to ~/
4. cd ~/TMCMR-master
5. chmod a+x Makefile
6. ./Makefile
That created a jar file
7. went into terminal and put in the required information and then it spit out this error 
Error: Could not find or load main class togos.minecraft.maprend.RegionRenderer

Not sure if I can put 2 issues in 1 but just a small side note: The downloadable file at http://www.nuke24.net/projects/TMCMR/ is corrupt and won't download completely.

**Comment by TOGoS** [comment] 2015-02-24 04:27
I apparently didn't do a very good quality-control job after generating the latest Jar file.  I'll look into this.

**Comment by TOGoS** [comment] 2015-02-24 05:06
The download link was broken because my web host changed the way in which you can force a file to be interpreted as a PHP script, so you were getting the PHP script that was supposed to serve the Jar file instead of the Jar file itself.  That is now fixed.  I will try to reproduce your Make troubles tomorrow.

**Comment by TOGoS** [comment] 2015-02-24 14:13
> 5. chmod a+x Makefile
> 6. ./Makefile

Okay, this one's user error.  Makefile isn't a shell script; it's a Makefile.  You run it by going into the directory and typing "make".

**Closed by TOGoS** 2015-02-24 14:13 UTC
